spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/redisProject?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dudwo123
    driver-class-name: com.mysql.cj.jdbc.Driver